### PR TITLE
Proposal to support alternate translations.

### PR DESCRIPTION
**Pull request by PaulRashidi**
This is primarily to start discussions about whether this is the correct structure.

### CODE REVIEW

**Comment by aaronj1335** [comment]
Pros: straightforward logic to falling back to english
Cons: every locale gets all translations

Other tradeoffs? Thoughts?

**Comment by aaronj1335** [comment]
Also, what's our mechanism for observing the change? Specifically, when you change languages and then go to the checklist, how does that activity know that you've changed?

**Comment by PaulRashidi** [comment]
This CL is a proposal to change the underlying FirebaseDB schema. Your question about changing languages is more of a client side switch which would then potentially listen and/or select data from this schema differently.

Pros: This initial proposal forces a relationship between the list items and translations by embedding them underneath as overrides. This makes it easier to update the data in the DB because you simply need to insert it underneath the correct element.
Cons: As initially proposed the alternate language data would be embedded underneath the checklist item. This would result in every client loading all of the alternate language translations when querying for a checklist item.

**Comment by aaronj1335** [comment]
Those tradeoffs make sense, and I think the proposal is the right way to go.

So if we went with this proposal, given that we're just [using a ref of all the checklist items in the activity](https://github.com/g11x/checklistapp/pull/25/files#diff-9bd930da412a0cea049300a7a63ad830R49), how would the activity know to use different strings when the user changes the language?

**Comment by PaulRashidi** [comment]
Client side, the logic needs to look to see whether the user choose a system override in the language screen I'm building. If they did it would load the defaults as well as the override. It would overlay the override values over the default values.

**Comment by PaulRashidi** [comment]
As discussed, Alt2 allows text overrides at the list level. This prevent clients from having to download all of the languages when using an alternate language.

**Comment by aaronj1335** [comment]
:shipit:

**Pull request merged**
